
version: 0.2

env:
  variables:
    API_URL: "https://2r1jycdqag.execute-api.us-east-1.amazonaws.com/Prod/detect-errors/"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y jq

  build:
    commands:
      - echo "Running calculator application..."
      - python calculator.py 2>&1 | tee build.log

  post_build:
    commands:
      - echo "Preparing logs for AI analysis..."
      - |
        # Read log file and format as JSON array
        LOG_JSON="["
        while IFS= read -r line; do
            escaped_line=$(echo "$line" | sed 's/"/\\"/g')
            LOG_JSON="$LOG_JSON\"$escaped_line\","
        done < build.log
        LOG_JSON="${LOG_JSON%,}]"
        
        # Create full payload
        JSON_PAYLOAD="{\"log_lines\": $LOG_JSON}"
        
        echo "Sending logs to AI API..."
        RESPONSE=$(curl -s -X POST "$API_URL" -H "Content-Type: application/json" -d "$JSON_PAYLOAD")
        
        echo "AI Response:"
        echo "$RESPONSE" | jq .
        
        ERRORS_FOUND=$(echo "$RESPONSE" | jq -r '.errors_found')
        if [ "$ERRORS_FOUND" = "true" ]; then
            echo "AI detected errors! Build failed."
            exit 1
        else
            echo "No errors detected. Build succeeded."
        fi
